/* Motor <motor.devel@gmail.com>
   see LICENSE for detail */
#ifndef MOTOR_META_BUILTINS_NUMBERS_HH
#define MOTOR_META_BUILTINS_NUMBERS_HH

#include <motor/meta/stdafx.h>
#include <motor/meta/classinfo.hh>

namespace Motor { namespace Meta {
MOTOR_DECLARE_CLASS_ID(META, bool)
MOTOR_DECLARE_CLASS_ID(META, i8)
MOTOR_DECLARE_CLASS_ID(META, u8)
MOTOR_DECLARE_CLASS_ID(META, i16)
MOTOR_DECLARE_CLASS_ID(META, u16)
MOTOR_DECLARE_CLASS_ID(META, i32)
MOTOR_DECLARE_CLASS_ID(META, u32)
MOTOR_DECLARE_CLASS_ID(META, i64)
MOTOR_DECLARE_CLASS_ID(META, u64)
MOTOR_DECLARE_CLASS_ID(META, float)
MOTOR_DECLARE_CLASS_ID(META, double)
}} // namespace Motor::Meta

#endif
