[workspace]
resolver = "2"
members = [
    "mak/bin/boltbuild",
    "mak/bin/flison",
    "mak/bin/metagen",
    "mak/lib/grammetica/grammetica-lib",
    #"mak/lib/grammetica/grammetica-cxx",
    "mak/lib/grammetica/grammetica",
    "mak/lib/rustixx",
]