version: 2.1

orbs:
  win: circleci/windows@5.0
  android: circleci/android@3.0.2

jobs:
  android:
    executor:
      name: android/android_machine
      tag: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: sudo apt update && sudo apt install -y flex bison
      - run:
          name: Configure
          command: python3 waf configure
      - run:
          name: Build Android 10 Clang 17.0.2
          command: python3 waf build:android_10-clang-17.0.2:debug --werror
      - run:
          name: Build Android 10 Clang 18.0.3
          command: python3 waf build:android_10-clang-18.0.3:debug --werror
      - run:
          name: Build Android 15 Clang 17.0.2
          command: python3 waf build:android_15-clang-17.0.2:debug --werror
      - run:
          name: Build Android 15 Clang 18.0.3
          command: python3 waf build:android_15-clang-18.0.3:debug --werror

  windows:
    executor:
      name: win/server-2022
    steps:
      - checkout
      - run:
          name: Configure
          command: |
            & 'python' waf configure
      - run:
          name: Build Windows MSVC 2017 x64
          command: |
            & 'python' waf build:windows_amd64-msvc_x64-14.16:debug --tests --werror
      - run:
          name: Build Windows MSVC 2019 x64
          command: |
            & 'python' waf build:windows_amd64-msvc_x64-14.29:debug --tests --werror
      - run:
          name: Build Windows MSVC 2019 ARM64
          command: |
            & 'python' waf build:windows_arm64-msvc_arm64-14.29:debug --werror
      - run:
          name: Build Windows MSVC 2022 x64
          command: |
            & 'python' waf build:windows_amd64-msvc_x64-14.42:debug --tests --werror
      - run:
          name: Build Windows MSVC 2022 ARM64
          command: |
            & 'python' waf build:windows_arm64-msvc_arm64-14.42:debug --werror
      - run:
          name: Build Windows Clang+MSVC 16.0.5
          command: |
            & 'python' waf build:windows_msvc_amd64-clang_buildtools2022_amd64-18.1.8:debug --werror

  macOS:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      - run:
          name: Configure
          command: python3 waf configure
      - run:
          name: Build macOS
          command: python3 waf build:macos14.5-appleclang-16.0.0:debug --werror

  iOS:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      - run:
          name: Configure
          command: python3 waf configure
      - run:
          name: Build iOS
          command: python3 waf build:iphone18.2-appleclang-16.0.0:debug --werror
      - run:
          name: Build iOS Simulator
          command: python3 waf build:iphonesimulator18.2_amd64-appleclang_amd64-16.0.0:debug --werror

  linux:
    docker:
      - image: motordev/motor:latest
    steps:
      - checkout
      - run:
          name: Configure
          command: python3 waf configure
      - run:
          name: Build GCC Debug
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:debug --tests --werror
      - run:
          name: Build GCC Debug static
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:debug --tests --static --werror
      - run:
          name: Build GCC Debug dynamic
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:debug --tests --dynamic --werror
      - run:
          name: Build GCC Debug without master
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:debug --tests --nomaster --werror
      - run:
          name: Build GCC Profile
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:profile --tests --werror
      - run:
          name: Build GCC Profile static
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:profile --tests --static --werror
      - run:
          name: Build GCC Profile dynamic
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:profile --tests --dynamic --werror
      - run:
          name: Build GCC Profile without master
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:profile --tests --nomaster --werror
      - run:
          name: Build GCC Final
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:final --tests --werror
      - run:
          name: Build GCC Final static
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:final --tests --static --werror
      - run:
          name: Build GCC Final dynamic
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:final --tests --dynamic --werror
      - run:
          name: Build GCC Final without master
          command: python3 waf build:redhat_linux_amd64-gcc_amd64-12.2.1:final --tests --nomaster --werror
      - run:
          name: Build Clang Debug
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:debug --tests --werror
      - run:
          name: Build Clang Debug static
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:debug --tests --static --werror
      - run:
          name: Build Clang Debug dynamic
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:debug --tests --dynamic --werror
      - run:
          name: Build Clang Debug without master
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:debug --tests --nomaster --werror
      - run:
          name: Build Clang Profile
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:profile --tests --werror
      - run:
          name: Build Clang Profile static
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:profile --tests --static --werror
      - run:
          name: Build Clang Profile dynamic
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:profile --tests --dynamic --werror
      - run:
          name: Build Clang Profile without master
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:profile --tests --nomaster --werror
      - run:
          name: Build Clang Final
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:final --tests --werror
      - run:
          name: Build Clang Final static
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:final --tests --static --werror
      - run:
          name: Build Clang Final dynamic
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:final --tests --dynamic --werror
      - run:
          name: Build Clang Final without master
          command: python3 waf build:linux_gnu_amd64-clang_amd64-14.0.5:final --tests --nomaster --werror

workflows:
  version: 2
  build:
    jobs:
      - linux
      - macOS
      - windows
      - android
      - iOS
