version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Configure
          command: python waf configure
      - run:
          name: Build Windows MSVC 14.0 x64
          command: python waf build:windows_amd64-msvc_x64-14.0:debug --tests
      - run:
          name: Build Windows MSVC 14.0 x86
          command: python waf build:windows_x86-msvc_amd64_x86-14.0:debug
      - run:
          name: Build Windows MSVC 14.0 ARM
          command: python waf build:windows_armv7a-msvc_amd64_arm-14.0:debug
      - run:
          name: Build Android Nougat GCC
          command: python waf build:android_nougat_7.1-gcc-4.9.x:debug
      - run:
          name: Build Android Nougat Clang
          command: python waf build:android_nougat_7.1-clang-5.0.300080:debug

  macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Configure
          command: python waf configure

  linux:
    docker:
      - image: motordev/motor:latest
    steps:
      - checkout
      - run:
          name: Configure
          command: python waf configure
      - run:
          name: Build GCC Debug
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:debug --tests
      - run:
          name: Build GCC Debug static
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:debug --tests --static
      - run:
          name: Build GCC Debug dynamic
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:debug --tests --dynamic
      - run:
          name: Build GCC Debug without master
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:debug --tests --nomaster
      - run:
          name: Build GCC Profile
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:profile --tests
      - run:
          name: Build GCC Profile static
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:profile --tests --static
      - run:
          name: Build GCC Profile dynamic
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:profile --tests --dynamic
      - run:
          name: Build GCC Profile without master
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:profile --tests --nomaster
      - run:
          name: Build GCC Final
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:final --tests
      - run:
          name: Build GCC Final static
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:final --tests --static
      - run:
          name: Build GCC Final dynamic
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:final --tests --dynamic
      - run:
          name: Build GCC Final without master
          command: python waf build:redhat_linux_amd64-gcc_amd64-7.3.1:final --tests --nomaster
      - run:
          name: Build Clang Debug
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:debug --tests
      - run:
          name: Build Clang Debug static
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:debug --tests --static
      - run:
          name: Build Clang Debug dynamic
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:debug --tests --dynamic
      - run:
          name: Build Clang Debug without master
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:debug --tests --nomaster
      - run:
          name: Build Clang Profile
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:profile --tests
      - run:
          name: Build Clang Profile static
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:profile --tests --static
      - run:
          name: Build Clang Profile dynamic
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:profile --tests --dynamic
      - run:
          name: Build Clang Profile without master
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:profile --tests --nomaster
      - run:
          name: Build Clang Final
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:final --tests
      - run:
          name: Build Clang Final static
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:final --tests --static
      - run:
          name: Build Clang Final dynamic
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:final --tests --dynamic
      - run:
          name: Build Clang Final without master
          command: python waf build:linux_gnu_amd64-clang_amd64-4.0.1:final --tests --nomaster

workflows:
  version: 2
  build:
    jobs:
      - linux
      - macos
      - windows
