from pyxx.ast.translation_unit import TranslationUnit
from typing import Optional, TextIO

__all__ = ['generate']


def generate(
    translation_unit: TranslationUnit, code_file: TextIO, documentation_file: TextIO, namespace_file: TextIO,
    stdafx: Optional[str]
):
    code_file.write('/* This file is automatically generated - do not edit. */')
    if stdafx:
        code_file.write('#include <%s>\n' % stdafx)
    code_file.write('\n')
