[package]
name = "boltbuild"
version = "0.1.0"
edition = "2021"
default-run = "boltbuild"

[dependencies]
mlua = { version = "~0.9.9", features = ["lua54", "vendored"] }
colored = "2.1"
clap = { version = "~4.5", features = ["string"] }
crossterm = "~0.28"
crossbeam = "~0.8"
glob = "~0.3"
blake3 = "~1.5"
regex = "~1.11"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
subprocess = "~0.2"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
include_dir = { version = "~0" }