[package]
name = "boltbuild"
version = "0.1.0"
edition = "2021"
default-run = "boltbuild"
description = "BoltBuild is a programmable build system."
license = "BSD-3-Clause"
homepage = "https://github.com/motor-dev/Motor"
repository = "https://github.com/motor-dev/Motor"

[features]
default = ["lua_debug"]
lua_debug = ["dep:cc", "dep:pkg-config"]
skip-pkg-config = []

[build-dependencies]
cc = { version = "~1", features = ["parallel"], optional = true }
pkg-config = { version = "0.3.17", optional = true }

[dependencies]
mlua = { version = "~0.10", features = ["lua54", "vendored", "userdata-wrappers"] }
colored = "~2"
clap = { version = "~4", features = ["string"] }
crossterm = "~0"
crossbeam = "~0"
glob = "~0"
blake3 = "~1"
regex = "~1"
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
subprocess = "~0"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
include_dir = { version = "~0" }
lazy_static = "~1"
flate2 = "1.0.35"
tar = "0.4.43"
diffy = "0.4.0"