#! /usr/bin/env python

import build_framework


def options(options_context: build_framework.OptionsContext) -> None:
    gr = options_context.get_option_group('SDK paths and options')
    assert gr is not None
    gr.add_option('--iphone-sdk-min',
                  action='store',
                  default='',
                  dest='iphone_sdk_min',
                  help='Minimum version of the iPhone SDK to target')
    gr.add_option('--iphone-sdk-max',
                  action='store',
                  default='',
                  dest='iphone_sdk_max',
                  help='Maximum version of the iPhone SDK to target')


def host_configure(configuration_context: build_framework.ConfigurationContext) -> None:
    configuration_context.recurse('mak/host_configure.py', name='host_configure')


def configure(configuration_context: build_framework.ConfigurationContext) -> None:
    configuration_context.recurse('mak/configure.py', name='configure')


def setup(setup_context: build_framework.SetupContext) -> None:
    setup_context.recurse('mak/setup.py', name='setup')


def build(build_context: build_framework.BuildContext) -> None:
    build_context.recurse('mak/build.py', name='build')
